version: "3"
volumes:
  postgresdb-data:
  minio-data:

services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - type: volume
        source: postgresdb-data
        target: /var/lib/postgresql/data
    container_name: db
    ports:
      - "5432:5432"
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: softserv
      MINIO_ROOT_PASSWORD: miniominio
    command: server --console-address ":9001" /data
