version: "3"
volumes:
  postgresdb-data:

services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - type: volume
        source: postgresdb-data
        target: /var/lib/postgresql/data
    container_name: db
    network_mode: "host"